---
- name: Get the list of VMs on the target machine.
  virt:
    command: list_vms
  register: list_vms

- name: Fail the play if there are remaining VMs.
  fail: 
    msg: "There are remaining VMs in the system"
  when: list_vms.list_vms|int > 0

- name: Get the list of libvirt networks on the target machine.
  virt_net:
    command: list_nets
    state: active
  register: active_netlist

- name: Deactivate the nat network.
  virt_net:
    command: destroy
    name: "{{ item.name }}"
  when: item.name in active_netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Get the list of libvirt networks on the target machine.
  virt_net:
    command: list_nets
  register: netlist

- name: Undefine the nat network.
  virt_net:
    command: undefine
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"