# Create Libvirt networks on a hypervisor.

# Depend on the following facts provided by load_facts:
# networks: The network parameters of the hypervisor.

# An optional parameter can be passed into this role:
# undefine: If this parameter is set, then the networks will be deleted from the hypervisor,
#           otherwise, the networks will be created on the hypervisor.

---
- name: Get list of defined networks
  virt_net:
    command: list_nets
  register: netlist

- fail: 
    msg: "network {{ item.name }} is present"
  when: item.name in netlist.list_nets and undefine is not defined
  with_items: '{{ networks }}'

- name: Deactivate if exists
  virt_net:
    command: destroy
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  with_items: '{{ networks }}'

- name: Undefine if exists
  virt_net:
    command: undefine
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  with_items: '{{ networks }}'

- name: Create the network
  virt_net:
    command=define
    name="{{ item.name }}"
    xml='{{ lookup("template", "../templates/virt-net.xml.j2") }}'
  with_items: '{{ networks }}'
  when: undefine is not defined

- name: Autostart it
  virt_net:
    name="{{ item.name }}"
    autostart='yes'
  with_items: '{{ networks }}'
  when: undefine is not defined

- name: Enable
  virt_net: 
    name={{ item.name }}
    state=active
  with_items: '{{ networks }}'
  when: undefine is not defined
