---
- name: List VMs
  virt:
    command: list_vms
  register: list_vms

- fail: 
    msg: "There are remaining VMs in the system"
  when: list_vms.list_vms|int > 0

- name: Get list of active networks
  virt_net:
    command: list_nets
    state: active
  register: active_netlist

- name: Deactivate if exists
  virt_net:
    command: destroy
    name: "{{ item.name }}"
  when: item.name in active_netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Get list of networks
  virt_net:
    command: list_nets
  register: netlist

- name: Undefine if exists
  virt_net:
    command: undefine
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"