# Tasks for installing Rust toolchain.
---
- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes

- name: Install curl and git.
  become: yes
  apt:
    name:
    - curl
    - git
    state: present

- name: "Install rust"
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"