---
- name: Check rustc exists.
  stat:
    path: "{{ rustc_bin_path }}"
  register: rustc_present

- name: Check cargo exists.
  stat:
    path: "{{ cargo_bin_path }}"
  register: cargo_present

- name: Check rustup exists.
  stat:
    path: "{{ rustup_bin_path }}"
  register: rustup_present

- name: Install Rust binaries.
  include_tasks: install_rust.yml
  when: rustup_present.stat.exists != true or cargo_present.stat.exists != true or rustc_present.stat.exists != true

- name: Update rustup
  shell: "{{ rustup_bin_path }} update"

- name: Install RLS
  shell: "{{ rustup_bin_path }} component add rls rust-analysis rust-src"

- name: Install cargo crates
  shell: "{{ cargo_bin_path }} install {{ item.crate }}"
  with_items: "{{ cargo_crates }}"
  when: cargo_crates is defined

- name: Checkout the development repository.
  git:
    repo: "{{ remote_repo }}"
    dest: "{{ local_repo }}"

- name: Install docker.io
  become: yes
  apt:
    name:
    - docker.io
    state: present
