---
- name: Check rustc exists.
  stat:
    path: "{{ rustc_bin_path }}"
  register: rustc_present

- name: Check cargo exists.
  stat:
    path: "{{ cargo_bin_path }}"
  register: cargo_present

- name: Check rustup exists.
  stat:
    path: "{{ rustup_bin_path }}"
  register: rustup_present

- name: Install Rust binaries.
  include_tasks: install_rust.yml
  when: rustup_present.stat.exists != true or cargo_present.stat.exists != true or rustc_present.stat.exists != true

- name: Update rustup
  shell: "{{ rustup_bin_path }} update"

- name: Install RLS
  shell: "{{ rustup_bin_path }} component add rls rust-analysis rust-src"

#- name: Update apt cache.
#  become: yes
#  apt:
#    update_cache: yes

#- name: Install curl and gcc.
#  become:
#  apt:
#    name:
#    - curl
#    - gcc
#    state: present

# - name: Detect Rust environment.
#   command: "/home/djp/.cargo/bin/rustc"
#   register: res

# - debug:
#     var: cargo_bin

# - debug:
#     var: rustc_bin

# - name: fuck
#   shell: "which apt"
#   register: res1

# - name: fuck1
#   shell: "cargo"
#   ignore_errors: true
#   register: res2

# - debug:
#     var: res1

# - debug:
#     var: res2

# - name: wtf
#   set_fact:
#     fubarhouse_user_dir: "{{ ansible_env.HOME }}"

# - name: "Rust | Define shell exports"
#   set_fact:
#     shell_exports:
#       - regex: 'export PATH="\$PATH:{{ fubarhouse_user_dir }}/.cargo/bin"'
#         lineinfile: 'export PATH="$PATH:{{ fubarhouse_user_dir }}/.cargo/bin"'
#   when: shell_exports is not defined

# - debug:
#     var: shell_exports

# - debug:
#     var: shell_profiles