---
- name: List VMs
  virt:
    command: list_vms
  register: list_vms

- fail: 
    msg: "There are remaining VMs in the system"
  when: list_vms.list_vms|int > 0

- name: Show bridge interface.
  command: "ip link show {{ vxlan.bridge_name }}"
  ignore_errors: yes
  register: show_bridge_interface

- fail: 
    msg: "bridge interface {{ vxlan.bridge_name }} is not present"
  when: show_bridge_interface.rc|int != 0

- name: Show vxlan interfaces.
  command: "ip link show vxlan{{ item.id }}"
  ignore_errors: yes
  register: show_vxlan_interfaces
  with_items: "{{ vxlan.remotes }}"

- fail: 
    msg: "vxlan interface vxlan{{ item.item.id }} is not present"
  when: item.rc|int != 0
  with_items: "{{ show_vxlan_interfaces.results }}"

- name: Delete vxlan interfaces.
  become: yes
  command: "ip link delete vxlan{{ item.id }}"
  with_items: '{{ vxlan.remotes }}'

- name: Delete bridge interface.
  become: yes
  command: "ip link delete {{ vxlan.bridge_name }}"

