# Upload a base VM image to the hypervisor.

# Depend on the following facts provided by load_facts role.
# cloud_img_dir: A sub-directory of the work space for storing the base VM image.
# base_img_name: The name of the base VM image.

# Expect the following variable:
# path_to_file: the path to the VM image for uploading
---
- name: Upload the base VM image to the hypervisor
  copy:
    src: "{{ path_to_file }}"
    dest: "{{ cloud_img_dir }}/{{ base_img_name }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"