# Create a work space in the home directory. 

# Depend on the following facts provided by load_facts:
# work_space_dir: The directory of the work space.
# cloud_img_dir: A sub-directory of the work space for storing the base VM image.
# vm_imgs_dir: A sub-directory of the work space for storing VM images.

---
- name: Create $HOME/WorkSpace
  file:
    path: "{{ work_space_dir }}"
    state: directory

- name: Create $HOME/CloudImg
  file:
    path: "{{ cloud_img_dir }}"
    state: directory

- name: Create $HOME/VMImgs
  file:
    path: "{{ vm_imgs_dir }}"
    state: directory

- name: Create $HOME/VMImgs
  file:
    path: "{{ work_space_dir }}/ansible"
    state: directory
