# Create a nat network on each target machine.

---
- hosts: dellservers
  remote_user: djp

  roles:
  - role: roles/load_vars
  - role: roles/networks/create_nat_network
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
