# Delete the nat network from the target machine.

# Then delete the veth pair created when configuring the bridge networks.

---
- hosts: dellservers
  remote_user: djp

  roles:
  - role: roles/load_vars
  - role: roles/networks/delete_nat_network
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"

- hosts: djp01
  become: yes
  vars:
    bport: bport

  tasks:
  - name: Show bport interface.
    command: "ip link show {{ bport }}"
    ignore_errors: yes
    register: show_bport

  - name: Delete bport.
    command: "ip link delete {{ bport }}"
    when: show_bport.rc|int == 0