---
# - name: Get list of active networks
#   virt_net:
#     command: list_nets
#     state: active
#   register: active_netlist

# - fail: 
#     msg: "network {{ item.name }} is not present"
#   when: item.name not in active_netlist.list_nets
#   with_items: '{{ networks }}'

- name: List existing VMs
  virt:
    command: list_vms
  register: list_vms

- name: Create VM images
  copy: 
    src: "{{ cloud_img_dir }}/{{ base_img_name }}"
    dest: "{{ vm_imgs_dir }}/vm{{ item.network_idx }}.img"
    remote_src: yes
  when: (("vm" + item.network_idx|string) not in list_vms.list_vms)
  with_items: '{{ vms }}'

- name: Define VMs.
  virt:
    command: define
    name: vm{{ item.network_idx }}
    xml: '{{ lookup("template", "../templates/vm.xml.j2") }}'
  when: ("vm" + item.network_idx|string) not in list_vms.list_vms
  with_items: "{{ vms }}"

- name: Start VMs
  virt:
    name: vm{{ item.network_idx }}
    state: running
  when: ("vm" + item.network_idx|string) not in list_vms.list_vms
  with_items: "{{ vms }}"