---
- name: List existing VMs
  virt:
    command: list_vms
  register: list_vms

- fail: 
    msg: "vm{{ item.network_idx }} is present"
  when: ("vm" + item.network_idx|string) in list_vms.list_vms and (item.network_idx|int < networks|length) 
  with_items: '{{ vms }}'

- name: Create VM images
  copy: 
    src: "{{ cloud_img_dir }}/{{ base_img_name }}"
    dest: "{{ vm_imgs_dir }}/vm{{ item.network_idx }}.img"
    remote_src: yes
  with_items: '{{ vms }}'

- name: Define VMs.
  virt:
    command: define
    name: vm{{ item.network_idx }}
    xml: '{{ lookup("template", "../templates/vm.xml.j2") }}'
  with_items: "{{ vms }}"

- name: Start VMs
  virt:
    name: vm{{ item.network_idx }}
    state: running
  with_items: "{{ vms }}"