# Check whether the VMs have successfully booted up by pinging to the VMs.

# Note: Please add "host_key_checking = False" to /etc/ansible/ansible.cfg for
#       each target machine. Otherwise the remote login may fail.

---
- hosts: dellservers

  roles:
  - role: roles/load_vars
  - role: roles/vms/check_bootup
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"