---
- hosts: dellservers

  roles:
  - role: roles/load_vars
  - role: roles/vms/check_bootup
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"