---
- hosts: dellservers

  roles:
  - role: roles/load_vars
  - role: roles/networks/config_bridge_networks
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"