---
- hosts: dellservers
  remote_user: djp

  roles:
  - role: roles/load_vars
  - role: roles/networks/delete_nat_network
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"