---
- hosts: dellservers

  roles:
  - role: roles/load_vars
  - role: roles/vnets/config_bridge_network
    vars:
      networks: "{{ network_param[inventory_hostname] }}"
      vms: "{{ vm_param[inventory_hostname] }}"