# Create Libvirt networks on a hypervisor.

# Depend on the following facts provided by load_facts:
# networks: The network parameters of the hypervisor.

# An optional parameter can be passed into this role:
# undefine: If this parameter is set, then the networks will be deleted from the hypervisor,
#           otherwise, the networks will be created on the hypervisor.

---
- name: Get the list of libvirt networks on the target machine.
  virt_net:
    command: list_nets
  register: netlist

- name: Create the nat network.
  virt_net:
    command=define
    name="{{ item.name }}"
    xml='{{ lookup("template", "../templates/virt-net.xml.j2") }}'
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Autostart the nat network.
  virt_net:
    name="{{ item.name }}"
    autostart='yes'
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Enable the nat network.
  virt_net: 
    name={{ item.name }}
    state=active
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"
