# Install necessaries packages and turn the machine into a hypervisor.

---
- name: Install necessary packages to become an hypervisor
  become: yes
  apt:
    pkg:
    - qemu-kvm
    - libvirt-bin
    - bridge-utils
    - python3-lxml
    - python3-libvirt
    - ansible
    - sshpass