# Provide facts used by other roles.
---

- include_vars: network_param.yml
- include_vars: vm_param.yml

- name: Set host facts used by other roles.  
  set_fact:
    # Host facts used by create_workspace
    work_space_dir: "{{ ansible_env.HOME }}/WorkSpace"
    cloud_img_dir: "{{ ansible_env.HOME }}/WorkSpace/CloudImg"
    vm_imgs_dir: "{{ ansible_env.HOME }}/WorkSpace/VMImgs"

    # Host facts used by upload_base_img
    base_img_name: baseimg.img

    # Parameters of the hypervisor network
    networks: "{{ lookup('vars', 'network_param_' + inventory_hostname) }}"

    # Parameters of the VMs
    vms: "{{ lookup('vars', 'vm_param_' + inventory_hostname) }}"