# Create a work space in the home directory. 

# Before using this role, please load the variables specified in load_vars/vars/workspace_param.yml.

---
- name: Create $HOME/WorkSpace
  file:
    path: "{{ work_space_dir }}"
    state: directory

- name: Create $HOME/CloudImg
  file:
    path: "{{ cloud_img_dir }}"
    state: directory

- name: Create $HOME/VMImgs
  file:
    path: "{{ vm_imgs_dir }}"
    state: directory

- name: Create $HOME/VMImgs
  file:
    path: "{{ work_space_dir }}/ansible"
    state: directory
