# Load variables from files in vars directory.

# This role should be loaded before using other roles

---
- name: Include workspace parameters.
  include_vars: workspace_param.yml
- name: Include network parameters.
  include_vars: 
    file: network_param.yml
    name: network_param
- name: Include VM parameters.
  include_vars: 
    file: vm_param1.yml
    name: vm_param