# Create Libvirt networks on a hypervisor.

# Depend on the following facts provided by load_facts:
# networks: The network parameters of the hypervisor.

# An optional parameter can be passed into this role:
# undefine: If this parameter is set, then the networks will be deleted from the hypervisor,
#           otherwise, the networks will be created on the hypervisor.

---
- name: Get list of defined networks
  virt_net:
    command: list_nets
  register: netlist

- name: Create the network
  virt_net:
    command=define
    name="{{ item.name }}"
    xml='{{ lookup("template", "../templates/virt-net.xml.j2") }}'
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Autostart it
  virt_net:
    name="{{ item.name }}"
    autostart='yes'
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"

- name: Enable
  virt_net: 
    name={{ item.name }}
    state=active
  when: item.name not in netlist.list_nets
  vars:
    item: "{{ networks.nat_network }}"
