# Upload a base VM image to the hypervisor.

# Before using this role, please load the variables specified in load_vars/vars/workspace_param.yml.

# Expect the following variable:
# path_to_file: the path to the VM image for uploading

---
- name: Upload the base VM image to the hypervisor
  copy:
    src: "{{ path_to_file }}"
    dest: "{{ cloud_img_dir }}/{{ base_img_name }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"