---
- name: List running VMs
  virt:
    command: list_vms
    state: running
  register: active_list_vms

- name: Destroy active VMs.
  virt:
    command: destroy
    name: "{{ item }}"
  with_items: "{{ active_list_vms.list_vms }}"

- name: List shutdown VMs
  virt:
    command: list_vms
  register: list_vms

- name: Undefine VMs
  virt:
    command: undefine
    name: "{{ item }}"
  with_items: "{{ list_vms.list_vms }}"

- name: Find all VM images
  find:
    paths: "{{ vm_imgs_dir }}"
    patterns: "*.img"
  register: images_to_delete

- name: Remove VM images.
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ images_to_delete.files }}"